name: fhir_stu3
description: FHIR library for supporing the Stu3 Version of FHIR for Dart & Flutter.
version: 0.1.0
homepage: https://www.fhirfli.dev/
repository: https://github.com/fhir-fli/fhir_stu3

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  archive: ^3.5.0
  collection: ^1.18.0
  fhir_primitives: ^0.1.0
  freezed_annotation: ^2.4.1
  hive: ^2.2.3
  http: ^1.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  mime: ^1.0.5
  mockito: ^5.4.4
  petitparser: ^6.0.2
  rxdart: ^0.27.2
  ucum: ^0.5.0
  universal_io: ^2.2.2
  uuid: ^4.4.0
  xml: ^6.5.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  # dart run import_sorter:main
  import_sorter: ^4.6.0
  json_serializable: ^6.8.0
  test: ^1.25.4
