name: fhir_stu3
description: FHIR library for supporing the Stu3 Version of FHIR for Dart & Flutter.
version: 0.1.0
homepage: https://www.fhirfli.dev/
repository: https://github.com/fhir-fli/fhir_stu3

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  archive: ^3.4.5
  collection: ^1.18.0

  fhir_primitives:
    path: ../fhir_primitives
  fhir_yaml:
    path: ../fhir_yaml
  freezed_annotation: ^2.4.1
  hive: ^2.2.3
  http: ^1.2.1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  mime: ^1.0.4
  mockito: ^5.4.4
  petitparser: ^6.0.2
  ucum: 
    path: ../ucum
  universal_io: ^2.2.2
  uuid: ^4.3.3
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7
  # dart run import_sorter:main
  import_sorter: ^4.6.0
  json_serializable: ^6.7.1
  test: ^1.25.2
